name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: '22'  # Set this to the version of Node.js you are using

    #   - name: Install Dependencies
    #     run: npm install

    #   - name: Build Project
    #     run: npm run generate  # Use 'generate' for Nuxt static site generation

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_DUNE_02E1D9C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          # app_build_command: 'npm run generate'  # This is the build command for Nuxt
          app_location: '/'  # Set this to the location of your application code
          api_location: '.output/server' # Api source code path - optional
          output_location: '.output/public'  # Ensure this matches the Nuxt output directory

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_DUNE_02E1D9C03 }}
          action: "close"
